export const ADD_POKEMON = 'ADD_POKEMON';       // Add a Pokemon to the store
// export const ADD_POKEMONS = 'ADD_POKEMONS';     // Add Pokemons to the store
export const SEARCH_POKEMON_BY_NAME = 'SEARCH_POKEMON_BY_NAME'; // Search pokemon in allPokemons state and put it in selectedPokemons state
export const SEARCH_POKEMON_BY_ID = 'SEARCH_POKEMON_BY_ID'; // Search pokemon in allPokemons state and put it in selectedPokemons state
export const FILTER_POKEMONS_BY_TYPE = 'FILTER_POKEMONS_BY_TYPE'; // Filter the Pokemons in the store
export const FILTER_POKEMONS_BY_SOURCE = 'FILTER_POKEMONS_BY_SOURCE'; // Filter the Pokemons in the store
export const ORDER_POKEMONS_BY_NAME = 'ORDER_POKEMONS_BY_NAME'; // Order Pokemons in the store
export const ORDER_POKEMONS_BY_ATTACK = 'ORDER_POKEMONS_BY_ATTACK'; // Order Pokemons in the store
export const RESET_POKEMONS_FILTERS = 'RESET_POKEMONS_FILTERS';   // Reset applied filters in store
export const GET_POKEMONS = 'GET_POKEMONS';    // Get all Pokemons from backend into store